Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "ex01" do |ex01|
    ex01.vm.hostname = "ex01"
    ex01.vm.network "private_network", ip: "192.168.56.101"
  end

  config.vm.define "ex02" do |ex02|
    ex02.vm.hostname = "ex02"
    ex02.vm.network "private_network", ip: "192.168.56.102"
  end

  config.vm.define "ex03" do |ex03|
    ex03.vm.hostname = "ex03"
    ex03.vm.network "private_network", ip: "192.168.56.103"
  end

  config.vm.define "ex04" do |ex04|
    ex04.vm.hostname = "ex04"
    ex04.vm.network "private_network", ip: "192.168.56.104"
  end
end
