Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = "debian/bookworm64"

  ['ex01', 'ex02', 'ex03', 'ex04'].each_with_index do |name, i|
    config.vm.define name do |vm|
      vm.vm.hostname = name
      vm.vm.network "private_network", ip: "192.168.56.10#{i + 1}"
      vm.vm.provision "ansible" do |ansible|
        ansible.playbook = "provisioning/site.yml"
        ansible.limit = name
      end
    end
  end
end
