---
- name: Ensure access for vagrant and student
  hosts: all
  become: yes
  tasks:
    - name: Ensure vagrant user exists with known password
      user:
        name: vagrant
        password: "{{ 'vagrant' | password_hash('sha512') }}"
        groups: sudo
        shell: /bin/bash
        state: present

    - name: Ensure .ssh directory exists for vagrant
      file:
        path: /home/vagrant/.ssh
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0700'

    - name: Add insecure public key to vagrant user
      copy:
        dest: /home/vagrant/.ssh/authorized_keys
        content: |
          ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA7QAAAQEAnzH77UjF8zD3aRqZx5cduMjb9Fz7EZUzZw1k4k3TWzXeHbhn8LgDZFv5ZWtOYjJToG8Z6z2TWZ4ovldJZPKNTdN3WkRACc4cNf0Z8iQdbKnU0h4KcGkV+H7omV3S0PuBaGJmQKlhJ5LzZrAvwl0tHewq8aElXrkZVxDFJYjOvQaxHEzOzV5EGk7qvTLdoHu3mIQQqhPaJ00tEN0hBRy3SRYMBLEwIDAQAB
        owner: vagrant
        group: vagrant
        mode: '0600'

    - name: Ensure student user exists with known password
      user:
        name: student
        password: "{{ 'startPentest' | password_hash('sha512') }}"
        groups: sudo
        shell: /bin/bash
        state: present

    - name: Ensure password auth is enabled in SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'

    - name: Ensure PermitRootLogin is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted